SELECT *
FROM EMPLOYEE;

SELECT *
FROM DEPARTMENT;

SELECT *
FROM JOB;

--문제7.
-- 입사한지 10년 이하인 사원의
-- 사원명, 직급명, 부서명, 입사일을 조회하시오.

SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, HIRE_DATE
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE > ADD_MONTHS(SYSDATE,-12*10);

--2. 부서별 보너스를 받는 사원 수를 카운트하여
-- 부서명과 사원 수를 조회하시오

SELECT DEPT_TITLE, COUNT(*)
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE BONUS IS NOT NULL
GROUP BY DEPT_TITLE;


--6. 사원 중에서 동일한 월급을 받는 사원들을 찾아
-- 사원명과 직급명과 부서명 월급을 조회하시오
SELECT *
FROM JOB;

SELECT EMP_NAME"사원명", JOB_NAME"직급명", DEPT_TITLE "부서명", SALARY*12 + (SALARY*NVL(BONUS,0)) "연봉"
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE SALARY = (SELECT SALARY
                            FROM EMPLOYEE
                            GROUP BY SALARY
                            HAVING COUNT(SALARY)>1);

--문제 15.
-- 급여 평균이 4위안에 드는 부서의
-- 순위번호(ROWNUM),부서명, 급여평균 조회 
-- ROWNUM과 인라인 뷰를 반영하여 작성, 급여 평균은 1000의자리까지)
-- 인라인 뷰 방식으로 작성

SELECT ROWNUM, DEPT_TITLE, SAL_AVG
FROM (SELECT DEPT_CODE,DEPT_TITLE, TRUNC(AVG(SALARY),-3) "SAL_AVG"
            FROM EMPLOYEE E
            JOIN DEPARTMENT D ON(DEPT_CODE= DEPT_ID)
            GROUP BY E.DEPT_CODE,D.DEPT_TITLE
            ORDER BY 3 DESC)
WHERE ROWNUM <4;



-- EMPLOYEE 테이블에서 사원의 이름과 급여를 조회하되,
-- SALARY 를 기준으로 1위에서 5위까지 출력하여라
-- DENSE_RANK( ) 사용, 인라인뷰 방식으로 조회.



SELECT *
FROM (SELECT DENSE_RANK() OVER(ORDER BY SALARY DESC)"순위", 
            EMP_NAME "사원명", SALARY "급여"
            FROM EMPLOYEE)
WHERE 순위<6;


SELECT EMP_ID "사번", EMP_NAME"이름",PHONE"휴대폰번호",DEPT_TITLE"부서명"
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE PHONE NOT LIKE '010%' AND SALARY<=3000000 AND EMPLOYEE.DEPT_CODE IS NOT NULL;


--문제10.
-- 나이가 어린 순으로 5명의 사원의
-- 사원명, 주민번호 앞 6자리, 직급코드, 월급을 조회하시오

SELECT *
FROM (SELECT EMP_NAME "사원명", RANK() OVER(ORDER BY SUBSTR(EMP_NO,1,6)DESC)"순위"
            ,SUBSTR(EMP_NO,1,6)"주민번호",DEPT_CODE"직급코드",SALARY "월급"
            FROM EMPLOYEE
            ORDER BY 주민번호 DESC)
WHERE 순위<6;


--문제11.
-- 한국에서 근무중인 사원들의 
-- 직급별 직급명과 보너스를 포함한 평균 연봉을 조회하시오.

SELECT *
FROM LOCATION;

SELECT *
FROM EMPLOYEE;

SELECT *
FROM DEPARTMENT;

SELECT *
FROM LOCATION;

SELECT JOB_NAME"직급명", AVG( (SALARY + (SALARY*NVL(BONUS,0)) )*12) "연봉"
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING(NATIONAL_CODE)
WHERE NATIONAL_NAME = '한국'
GROUP BY JOB_NAME;

SELECT JOB_NAME, AVG( (SALARY + (SALARY*NVL(BONUS,0)) )*12 )
FROM EMPLOYEE
JOIN department ON ( DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN national USING ( NATIONAL_CODE)
JOIN JOB USING(JOB_CODE)
WHERE NATIONAL_NAME = '한국'
GROUP BY JOB_NAME;
