SELECT *
FROM EMPLOYEE;

SELECT EMP_ID"사번", EMP_NAME"사원명", DEPT_TITLE "부서명"
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE BONUS IS NULL;


SELECT *
FROM NATIONAL;

SELECT *
FROM LOCATION;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM JOB;
--DEPT_CODE D6
--해외영업2부
--LOCATION_ID L3

SELECT EMP_NAME, JOB_NAME, PHONE, DEPT_TITLE 
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING(NATIONAL_CODE)
WHERE DEPT_CODE = 'D6';

--32
SELECT EMP_NAME, JOB_NAME, PHONE, DEPT_TITLE
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE NATIONAL_CODE = 'CH';



--장기 근속 사원 5명에게 상을 주려고한다
--근속연수를 기준으로 1~5위까지 상위 5명을 추려
--순위 사원명 부서명 근속연수(년) 를 조회하시오
--근속연수는 소수점이하 버림

SELECT RANK() OVER(ORDER BY FLOOR((SYSDATE - HIRE_DATE)/365))

FROM EMPLOYEE;






